/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.fredbrunel.android.twitter;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int logo=0x7f020001;
        public static final int refresh_icon=0x7f020002;
        public static final int twitalert=0x7f020003;
        public static final int twitmenubar=0x7f020004;
    }
    public static final class id {
        public static final int config_apply=0x7f050002;
        public static final int config_password=0x7f050001;
        public static final int config_username=0x7f050000;
        public static final int sample_text=0x7f050006;
        public static final int splash_logo=0x7f050007;
        public static final int status_list=0x7f050003;
        public static final int status_message=0x7f050005;
        public static final int status_refresh=0x7f050004;
    }
    public static final class layout {
        public static final int configure=0x7f030000;
        public static final int main=0x7f030001;
        public static final int sample=0x7f030002;
        public static final int splash=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int config_activity_name=0x7f040001;
        public static final int status_activity_name=0x7f040002;
        public static final int status_configure_menu=0x7f040004;
        public static final int status_message_placeholder=0x7f040003;
    }
}
